"""
Interactive tile labeler. Shows one candidate tile at a time from the
grid generated by sample_candidates.py — press a key to label it.

Controls:
    m = mine (positive)
    n = no_mine (negative)
    s = skip (uncertain / don't label)
    q = quit and save

Usage:
    python data/label_tool.py
"""
import json
import os

import numpy as np
import rasterio
import matplotlib.pyplot as plt

import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

TIF_PATH = "data/raw/zamfara_gold.tif"
POINTS_PATH = "data/candidate_points.json"
LABELS_PATH = os.path.join(config.LABELS_DIR, f"{config.ACTIVE_REGION}_labels.geojson")

CHIP_HALF = config.TILE_SIZE_PX // 2


def load_existing_labels():
    if os.path.exists(LABELS_PATH):
        with open(LABELS_PATH) as f:
            data = json.load(f)
        return data["features"]
    return []


def save_labels(features):
    geojson = {"type": "FeatureCollection", "features": features}
    with open(LABELS_PATH, "w") as f:
        json.dump(geojson, f, indent=2)
    print(f"Saved {len(features)} total labels to {LABELS_PATH}")


def already_labeled(features, lon, lat, tol=1e-6):
    for feat in features:
        clon, clat = feat["geometry"]["coordinates"]
        if abs(clon - lon) < tol and abs(clat - lat) < tol:
            return True
    return False


def main():
    with open(POINTS_PATH) as f:
        points = json.load(f)

    labels = load_existing_labels()
    print(f"Starting with {len(labels)} existing labels.")

    with rasterio.open(TIF_PATH) as src:
        img_full = src.read([1, 2, 3]).astype(np.float32)
        img_full = np.moveaxis(img_full, 0, -1)
        img_full = np.clip(img_full / np.percentile(img_full, 98), 0, 1)

        result = {"action": None}

        def on_key(event):
            result["action"] = event.key
            plt.close()

        for i, p in enumerate(points):
            row, col = p["row"], p["col"]
            lon, lat = p["lon"], p["lat"]

            if already_labeled(labels, lon, lat):
                continue

            r0, r1 = max(0, row - CHIP_HALF), row + CHIP_HALF
            c0, c1 = max(0, col - CHIP_HALF), col + CHIP_HALF
            chip = img_full[r0:r1, c0:c1]

            if chip.size == 0 or np.count_nonzero(chip) / chip.size < 0.5:
                continue  # skip empty/nodata chips automatically

            fig, ax = plt.subplots(figsize=(6, 6))
            ax.imshow(chip)
            ax.set_title(f"Point {i}/{len(points)} — m=mine  n=no_mine  s=skip  q=quit")
            ax.axis("off")
            fig.canvas.mpl_connect("key_press_event", on_key)
            plt.show()

            action = result["action"]
            if action == "q":
                break
            elif action == "m":
                labels.append({
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [lon, lat]},
                    "properties": {"mine": 1},
                })
                print(f"  -> labeled MINE ({len(labels)} total)")
            elif action == "n":
                labels.append({
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [lon, lat]},
                    "properties": {"mine": 0},
                })
                print(f"  -> labeled NO_MINE ({len(labels)} total)")
            else:
                print("  -> skipped")

            save_labels(labels)  # save after every label so nothing is lost

    print("Done.")


if __name__ == "__main__":
    main()